### ISSUE TITLE
Alerts table and endpoint

### ISSUE THREAD

**Issue by liustanley** [sandboxnu/office-hours#585]
**Milestone Goal: 3/7**

Should push alerts and modals from the backend
Also integrate SSE into this

- [ ] Alerts SWR lives in the NavBar or Container
- [ ] Add an endpoint for Alerts
- [ ] On an Alert, display a modal to the Student that they have to dismiss
- [ ] Clicking on the Alert would take you to the queue page to do the required action
- [ ] Alert table: `studentId, alertType, course`
- [ ] On dismiss, delete the Alert from the table
